// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed/index.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Shadow DB untuk `migrate dev`/`migrate diff --from-migrations` —
    // WAJIB di-set kalau DATABASE_URL menunjuk Postgres terkelola (Neon)
    // yang tidak mengizinkan CREATE DATABASE. Pakai Postgres lokal
    // docker-compose: postgresql://dev:dev@127.0.0.1:5432/shadow_uji
    // (database sekali-pakai, JANGAN tunjuk ke database berisi data).
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
